config/routes.rb
Rails.application.routes.draw do
  
  get 'searches/show'

  get 'subscriptions/create'

  get 'subscriptions/destroy'

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: "questions#index"
  
  resource :search, only: :show
  resources :questions, except: :edit do
    patch 'vote', on: :member
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :comments, only: [:new, :create], shallow: true
    resources :answers, only: [:create, :update, :destroy, :edit], shallow: true do
      resources :comments, only: [:new, :create], shallow: true
      patch 'set_best', on: :member
      patch 'vote', on: :member
    end
  end
  
  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions, except: [:new, :edit, :update] do
        resources :answers, except: [:new, :edit, :update], shallow: true
      end
    end
  end
  
  resources :attachments, only: [:destroy]
  
  mount ActionCable.server => '/cable'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Voteable
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true
  
  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank
  
  after_create { Subscription.create(user_id: self.user.id, question_id: id) }
  
  default_scope { order("created_at") }
  
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource
  
  def index
    @questions = Question.all
    respond_with @questions, each_serializer: QuestionListSerializer
  end
  
  def show
    @question = Question.find(params[:id])
    respond_with @question, serializer: SingleQuestionSerializer
  end
  
  def create
    @question = current_resource_owner.questions.create(question_params)
    respond_with @question
  end
  
  private
  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Votes
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :update, :destroy, :select_best_answer, :vote, :subscribe, :unsubscribe]
  after_action :publish_question, only: [:create]
  authorize_resource except: :vote
  skip_authorization_check only: :vote
  
  respond_to :html, :js

  def index
    respond_with(@questions = Question.all)
  end

  def show
    @answers = @question.answers
    @subscription = current_user.subscriptions.try(:find_by_question_id, @question) if current_user
    gon.current_user_id = current_user.id if user_signed_in?
    respond_with @question
  end

  def new
    @question = current_user.questions.build
    respond_with @question
  end
  
  def create
    @question = current_user.questions.create(question_params)
    respond_with @question
  end

  def update
    @question.update(question_params)
    respond_with @question
  end
  
  def destroy
    respond_with @question.destroy
  end
  
  private
  def set_question
    @question = Question.find(params[:id])
  end
  
  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast('questions',
      ApplicationController.render(
      partial: 'questions/question',
      locals: { question: @question }
      )
    )
  end

  def question_params
    params.require(:question).permit(:value, :title, :body, attachments_attributes: [:file, :_destroy, :id])
  end

end

app/views/questions/_attachments.html.slim
- if question.attachments.present?
  #attachments
    ul 
      = render question.attachments

app/views/questions/_buttons.html.slim
  -if can?(:edit, question)
    = link_to 'edit question', '#', id: 'edit-question-link'
    |  |     
  -if can?(:destroy, question)
    =link_to 'delete question', question_path(question), method: :delete, data: { confirm: 'Sure?' }
    |  |
  -if user_signed_in?
    =link_to 'add a comment', new_question_comment_path(question), remote: true
    |  |
  -if can?(:create, Subscription) && can?(:destroy, Subscription)
    -if subscription
      =link_to 'unsubscribe', subscription_path(subscription), method: :delete, id: 'subscription-button'
    -else  
      =link_to 'subscribe', question_subscriptions_path(question), method: :post, id: 'subscription-button'

app/views/questions/_form.html.slim
= nested_form_for question do |f|
  .form-group
    = f.label :title
    br
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :body
    = f.text_area :body, cols: 50, rows: 15, class: 'form-control'
  .form-group
    = f.fields_for :attachments do |a|
      = a.label :file
      = a.file_field :file
      = a.link_to_remove 'remove file'
    = f.link_to_add 'add file', :attachments
  .form-group
    = f.submit 'Create question', class: 'btn btn-default'

app/views/questions/_question.html.slim
tr
 td = question.answers.count
 td = link_to question.title, question_path(question)

app/views/questions/index.html.slim
p
  =link_to 'New question', new_question_path
  
h1 Questions list
table.table.table-hover#questions-list
  thead
    tr 
      th Answers
      th Title
    tbody
    -unless @questions.empty?
      = render @questions
    -else
      tr 
        td
    

app/views/questions/new.html.slim
h1 new question
= render 'common/errors', resource: @question
=render 'form', question: @question

app/views/questions/show.html.slim
-cache_unless current_user.try(:admin?), [can?(:vote, @question), can?(:edit, @question), can?(:destroy, @question), user_signed_in?, can?(:create, Subscription) && can?(:destroy, Subscription), @question]
  h1#caption= @question.title
  #question data-id="#{@question.id}"
    #question-body
      p= @question.body
    div id="question-#{@question.id}-attachments"
      = render 'attachments', question: @question
    #question-buttons
      = render 'buttons', question: @question, subscription: @subscription
      .question-rating
        -if can?(:vote, @question)
          =link_to '-', vote_question_path(@question, value: -1), method: :patch, remote: true, data: { type: :json }
        span id="question-#{@question.id}-rating"
          =<>@question.rating
        -if can?(:vote, @question)
          =link_to '+', vote_question_path(@question, value: 1), method: :patch, remote: true

          
    
  = nested_form_for @question, remote: true, html: { id: 'edit-question-form' } do |f|
    .form-group
      =f.label :title, 'Edit your question title:'
      =f.text_field :title, class: 'form-control'
    .form-group
      =f.label :body, 'Edit your question:'
      =f.text_area :body, class: 'form-control'
    .form-group
      = f.fields_for :attachments do |a|
        -if a.object.new_record?
          = a.label :file
          = a.object.class
          = a.file_field :file
          = a.link_to_remove 'remove'
      =f.link_to_add 'add file', :attachments
    =f.submit 'Save', class: 'btn btn-default'
    =link_to "Cancel", "#", class: "btn btn-default cancel"
  |comments:
  .div id="Question-#{@question.id}-comments" class = 'question-comments'
    =render @question.comments

  .answers
    table.table.table#answers
      tbody
        = render @answers

  = render 'common/errors', resource: @answer ||= @question.answers.build

  = nested_form_for [@question, @answer || @question.answers.build], remote: true do |f|
    .form-group
    = f.label :body, 'Answer:'
    .form-group
    = f.text_area :body, class: 'form-control'
    .form-group
    = f.fields_for :attachments do |a|
      =a.label :file
      =a.file_field :file
      =a.link_to_remove 'remove'
    = f.link_to_add 'add file', :attachments
    .form-group
    = f.submit 'Post your answer', class: 'btn btn-success'

       

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  $('div#errors-field').html(" <div class='alert fade in alert-danger'> <%= j render 'common/errors', resource: @question %> </div>")
<% else %>
  $('div#errors-field').html('')
  $('#question-body p').text(' <%= j @question.body %> ');
  $('#caption').text('<%= j @question.title %>');
  $('#question-' + '<%= @question.id %>' + '-attachments').html(' <%= j render 'attachments', question: @question %>' );
  $('#edit-question-form').hide();
  $('#edit-question-link').show();
<% end %>   