config/routes.rb
Rails.application.routes.draw do
  
  get 'searches/show'

  get 'subscriptions/create'

  get 'subscriptions/destroy'

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: "questions#index"
  
  resource :search, only: :show
  resources :questions, except: :edit do
    patch 'vote', on: :member
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :comments, only: [:new, :create], shallow: true
    resources :answers, only: [:create, :update, :destroy, :edit], shallow: true do
      resources :comments, only: [:new, :create], shallow: true
      patch 'set_best', on: :member
      patch 'vote', on: :member
    end
  end
  
  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions, except: [:new, :edit, :update] do
        resources :answers, except: [:new, :edit, :update], shallow: true
      end
    end
  end
  
  resources :attachments, only: [:destroy]
  
  mount ActionCable.server => '/cable'

end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true
  
  mount_uploader :file, FileUploader
  
  validates :file, presence: true
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  respond_to :js
  authorize_resource
  
  
  def destroy
    @attachment = Attachment.find(params[:id])
    @attachable = @attachment.attachable
    respond_with @attachment.destroy
  end
end

app/views/attachments/_attachment.html.slim
li
  = link_to attachment.file.identifier, attachment.file.url
  -if can?(:destroy, attachment)
    = link_to ' [x]  ', attachment_path(attachment), method: :delete, remote: true, data: { confirm: "Sure?"}

app/views/attachments/destroy.js.erb
attachable = '<%= "#{@attachable.class.name.underscore}-#{@attachable.id}-attachments" %>';
$('#' + attachable).html('<ul>' + ' <%= j render @attachable.attachments %>');