config/routes.rb
Rails.application.routes.draw do
  
  get 'searches/show'

  get 'subscriptions/create'

  get 'subscriptions/destroy'

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: "questions#index"
  
  resource :search, only: :show
  resources :questions, except: :edit do
    patch 'vote', on: :member
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :comments, only: [:new, :create], shallow: true
    resources :answers, only: [:create, :update, :destroy, :edit], shallow: true do
      resources :comments, only: [:new, :create], shallow: true
      patch 'set_best', on: :member
      patch 'vote', on: :member
    end
  end
  
  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions, except: [:new, :edit, :update] do
        resources :answers, except: [:new, :edit, :update], shallow: true
      end
    end
  end
  
  resources :attachments, only: [:destroy]
  
  mount ActionCable.server => '/cable'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Voteable
  belongs_to :user
  belongs_to :question, touch: true
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true, length: { minimum: 3 }
  validates :question_id, :user_id, presence: true
  default_scope { order('best DESC, created_at') }
    
  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank

  after_create { SendAnswerNewsletterJob.perform_later(self) }
  
    
  def set_best
    transaction do
      question.answers.where(best: true).update_all(best: false)
      update!(best: true)
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Votes
  before_action :authenticate_user!
  before_action :set_question, only: [:create]
  before_action :set_answer, only: [:update, :edit, :destroy, :set_best, :vote]
  after_action :publish_answer, only: [:create]
  
  authorize_resource except: :vote
  skip_authorization_check only: :vote
  
  respond_to :js, :json

  def create
    @answer = current_user.answers.create(answer_params.merge(question_id: @question.id))
    respond_with(@answer)
  end

  def edit
    respond_with(@answer)
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def destroy
    respond_with @answer.destroy
  end

  def set_best
    @answer.set_best
    @answers = @answer.question.answers
  end
  
  private
  def set_answer
    @answer = Answer.find(params[:id])
  end
  
  def publish_answer
    return if @answer.errors.any?
    data = {
      type: :answer,
      answer_user_id: current_user.id,
      question_user_id: @question.user_id,
      answer: @answer,
      answer_attachments: @answer.attachments
    }
    ActionCable.server.broadcast("question_answers_#{params[:question_id]}", data)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :_destroy, :id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource
  before_action :set_question, only: [:index, :create]
    
  def index
    @answers = @question.answers
    respond_with @answers, each_serializer: AnswerListSerializer
  end
  
  def show
    @answer = Answer.find(params[:id])
    respond_with @answer, serializer: SingleAnswerSerializer
  end
  
  def create
    @answer = current_resource_owner.answers.create(answer_params.merge(question_id: @question.id))
    respond_with @answer
  end
  
  private
  def set_question
    @question = Question.find(params[:question_id])
  end
  
  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.slim
-cache_unless current_user.try(:admin?), [can?(:set_best, answer) && !answer.best, can?(:edit, answer), user_signed_in?, can?(:vote, answer), answer] do
  - if answer.persisted?
    tr id="answer-#{answer.id}"
      td.best-column
        = render 'answers/glyphicon_ok' if answer.best?
      td
        div id="answer-#{answer.id}-body"
          = answer.body
        .answer-buttons
          -if  can?(:set_best, answer) && !answer.best
            =<>link_to 'select as best', set_best_answer_path(answer), method: :patch, id: 'select-as-best-link', remote: true
            | |  
          -if can?(:edit, answer)
            =<>link_to 'edit answer', edit_answer_path(answer), class: 'edit-answer-link', data: { answer_id: answer.id, remote: true }
            | |
            =<>link_to 'delete answer', answer, method: :delete, remote: true, class: "delete-answer-link", data: { answer_id: answer.id, confirm: 'Sure?' }
            | |
          -if user_signed_in?  
            =< link_to 'add a comment', new_answer_comment_path(answer), remote: true
          .answer-rating
            -if can?(:vote, answer)
              =link_to '-', vote_answer_path(answer, value: -1), method: :patch, remote: true, data: { type: :json }
            span id = "answer-#{answer.id}-rating"
              =<> answer.rating
            -if can?(:vote, answer)  
              =link_to '+', vote_answer_path(answer, value: 1), method: :patch, remote: true, data: { type: :json }  
          - if answer.attachments.present?
            ul 
              div id="answer-#{answer.id}-attachments"  
                = render answer.attachments
        div id="Answer-#{answer.id}-comments" class="answer-comments"
          = render answer.comments

app/views/answers/_edit_answer_form.html.slim
=form_for answer, remote: true, html: { id: "edit-answer-form-#{answer.id}"} do |f|
  .form-group
    =f.label :body, 'Edit your answer:'
    =f.text_area :body, class: 'form-control'
    =f.fields_for :attachments do |a| 
      =a.label :file
      =a.file_field :file, class: 'form-control'
  =f.submit 'Save', class: "btn btn-default"
  =link_to "Cancel", "#", class: "btn btn-default cancel" 
  

app/views/answers/_glyphicon_ok.html.slim
= image_tag 'OK.svg.png', id: 'best-icon'

app/views/answers/create.js.erb
<% if @answer.errors.any? %>
  $('#errors-field').html( " <div class='alert fade in alert-danger'><button type='button' class='close' data-dismiss='alert'>x</button> <%=  j render 'common/errors', resource: @answer %> </div>" );
<% else %> 
  $('#errors-field').html('') 
  $('textarea#answer_body').val('');
<% end %>  

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').remove();

app/views/answers/edit.js.erb
$("#answer-<%= @answer.id %> .answer-buttons").append("<%= j render 'answers/edit_answer_form', answer: @answer %>")

app/views/answers/redirect.js.erb
$('#caption').html("There was an error with your answer, not saved")

app/views/answers/set_best.js.erb
$('.answers tbody').html(" <%= j render @answers %>")

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  $('#errors-field').html('<div class="alert fade in alert-danger">' + "<%= j render 'common/errors', resource: @answer %>"  + '</div>' )
<% else %>
 $('#errors-field').html('')
 var answer_id = <%= @answer.id %>;
 $('form#edit-answer-form-' + answer_id).hide();
 $('*[data-answer-id="'+answer_id+'"]').show();
 $('#answer-' + answer_id + '-body').text('<%= j @answer.body %>')
<% end %>   