config/routes.rb
Rails.application.routes.draw do
  
  get 'searches/show'

  get 'subscriptions/create'

  get 'subscriptions/destroy'

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: "questions#index"
  
  resource :search, only: :show
  resources :questions, except: :edit do
    patch 'vote', on: :member
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :comments, only: [:new, :create], shallow: true
    resources :answers, only: [:create, :update, :destroy, :edit], shallow: true do
      resources :comments, only: [:new, :create], shallow: true
      patch 'set_best', on: :member
      patch 'vote', on: :member
    end
  end
  
  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions, except: [:new, :edit, :update] do
        resources :answers, except: [:new, :edit, :update], shallow: true
      end
    end
  end
  
  resources :attachments, only: [:destroy]
  
  mount ActionCable.server => '/cable'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Asky</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>

<% end %>  

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Asky"
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"



  body
    = include_gon init: true
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"Asky
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Questions list", questions_path
              li= link_to 'Search', search_path
              -if user_signed_in?
                li= link_to 'New question', new_question_path
                li= link_to "Log out (#{current_user.name})", destroy_user_session_path, method: :delete
              -else  
                li= link_to "Sign up", new_user_registration_path
                li= link_to "Log in", new_user_session_path

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          #errors-field
          = yield
        / .col-lg-3
        /   .well.sidebar-nav
        /     h3 Sidebar
        /     ul.nav.nav-list
        /       li.nav-header Sidebar
        /       li= link_to "Link 1", "/path1"
        /       li= link_to "Link 2", "/path2"
        /       li= link_to "Link 3", "/path3"

      footer
        p &copy; Company 2016